version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVER_URL=${SERVER_URL}
      - WEBHOOK_URL=https://gpt.${BOT_DOMAIN}
      - USE_WEBHOOK=${USE_WEBHOOK}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.bot.rule=Host(`gpt.${BOT_DOMAIN}`)
      - traefik.http.routers.bot.entrypoints=https
      - traefik.http.routers.bot.tls=true
      - traefik.http.routers.bot.tls.certresolver=letsencrypt
    networks:
      - traefik-public

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - traefik-public

volumes:
  postgres_data:

networks:
  traefik-public:
    external: true